export const trendingMovies = (state) => state.movies.items;
export const isLoading = (state) => state.movies.isLoading;
export const movieInfo = (state) => state.movies.movieInfo;
export const currentPage = (state) => state.movies.currentPage;
export const totalPages = (state) => state.movies.totalPages;
export const trailerMovie = (state) => state.movies.trailer;
export const foundMovies = (state) => state.movies.foundMovies;
export const castInfo = (state) => state.movies.castInfo;
export const reviewsInfo = (state) => state.movies.reviewsInfo;
